server:
  port: 8080


price-monitor:
  api-uri: http://${PRICE_MONITOR_HOST:localhost}:8888/api/v1/prices/{cryptoUnit}-USD/market-price

currency-monitor:
  api-uri: http://${CURRENCY_MONITOR_HOST:localhost}:9999/api/v1/currencies/{currency}